---
- name: 배포하기
  hosts: all
  become: yes
  tasks:
    - name: nginx 컨테이너 배포
      docker_container:
        name: nginx
        image: nginx
        restart_policy: on-failure
        networks:
          - name: web
        environment:
          SERVICE_PORTS: 80
        deploy:
          replicas: 2
          placement:
            constraints: [node.role != manager]
          resources:
            limits:
              cpus: '1'
              memory: '32M'

    - name: proxy 컨테이너 배포
      docker_container:
        name: proxy
        image: dockercloud/haproxy
        depends_on: nginx
        ports:
          - "8000:80"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
          - name: web
        deploy:
          mode: global
          placement:
            constraints: [node.role == manager]

    - name: web 네트워크 생성
      docker_network:
        name: web
        driver: overlay
        state: present
