---
- name: 배포하기
  hosts: all
  become: yes
  tasks:
    - name: nginx 서비스 배포
      docker_service:
        project_src: /path/to/docker-compose.yml
        state: present
        definition:
          version: '3'
          services:
            nginx:
              image: nginx
              deploy:
                replicas: 2
                resources:
                  limits:
                    cpus: '1'
                    memory: '32M'
              environment:
                SERVICE_PORTS: 80
              networks:
                - web

            proxy:
              image: dockercloud/haproxy
              depends_on:
                - nginx
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
              ports:
                - 8000:80
              networks:
                - web
              deploy:
                mode: global
                placement:
                  constraints: [node.role == manager]

          networks:
            web:
              external: true
